package com.temenos;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ACCOUNT_ODDAYS implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("OVERDUE_DAYS")
	private java.lang.Integer OVERDUE_DAYS;

	public ACCOUNT_ODDAYS() {
	}

	public java.lang.Integer getOVERDUE_DAYS() {
		return this.OVERDUE_DAYS;
	}

	public void setOVERDUE_DAYS(java.lang.Integer OVERDUE_DAYS) {
		this.OVERDUE_DAYS = OVERDUE_DAYS;
	}

	public ACCOUNT_ODDAYS(java.lang.Integer OVERDUE_DAYS) {
		this.OVERDUE_DAYS = OVERDUE_DAYS;
	}

}