package com.temenos;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class AR_CUSTOMER_CHARGE implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "VARIATION")
	private java.lang.String VARIATION;

	public AR_CUSTOMER_CHARGE() {
	}

	public java.lang.String getVARIATION() {
		return this.VARIATION;
	}

	public void setVARIATION(java.lang.String VARIATION) {
		this.VARIATION = VARIATION;
	}

	public AR_CUSTOMER_CHARGE(java.lang.String VARIATION) {
		this.VARIATION = VARIATION;
	}

}